name: Run Pytest Tests #Code success with HTML report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest junit2html 

      - name: Verify Installed Packages
        run: pip list

      - name: Debug Pytest Test Discovery
        run: pytest --collect-only  # Check if pytest can find the tests

      - name: Run tests and generate report  # Run tests with verbose output
        id: pytest_run
        run: |
          pytest --junitxml=test-results.xml -v | tee pytest_output.log
          EXIT_CODE=${PIPESTATUS[0]}  # Capture pytest exit code
          echo "Pytest completed with exit code $EXIT_CODE"
          cp pytest_output.log /tmp/pytest_output.log  # Store output for later use
          exit $EXIT_CODE  # Ensure the correct exit code is returned to GitHub Actions

      - name: Show Test Summary
        run: |
          echo "======= Pytest Test Summary ======="
          if [ -s pytest_output.log ]; then  # Check if the file exists and is not empty
             cat pytest_output.log
          else
            echo "No pytest output available."
          fi

      - name: Convert XML to HTML Report
        if: always()
        run: |
          if [ -f test-results.xml ]; then
            python -m pip install --upgrade pip
            python -m pip install junit2html  
            ~/.local/bin/junit2html test-results.xml test-report.html || junit2html test-results.xml test-report.html
          else
            echo "No test-results.xml found, skipping HTML conversion."
          fi

      - name: Upload HTML Test Report  # Ensures report is uploaded even if tests fail
        if: always()  
        uses: actions/upload-artifact@v4 
        with:
          name: pytest-html-report
          path: test-report.html  # Upload the test report
