name: Run Pytest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Debug Pytest Test Discovery
        run: pytest --collect-only  # Check if pytest can find the tests

      - name: Run tests and generate report  # run tests with verbose output
        run: pytest --junitxml=test-results.xml -v # Run pytest without specifying a folder

      - name: Show Test Summary
        run: |
          pip install junit2html
          junit2html test-results.xml test-report.html  # Convert to HTML
          cat pytest_output.log | tail -20  # Show the last 20 lines of test output

      - name: Upload test report  # Ensures report is uploaded even if tests fail
        if: always()  
        uses: actions/upload-artifact@v4 
        with:
          name: pytest-report
          path: test-results.xml  # Upload the test report