name: Run Pytest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests and generate report
        run: pytest PYTHON-TESTING --junitxml=test-results.xml  # Generate test report

      - name: Upload test report
        if: always()  # Ensures report is uploaded even if tests fail
        uses: actions/upload-artifact@v4 
        with:
          name: pytest-report
          path: test-results.xml  # Upload the test report